[#15] Replaces yapf with autopep8

diff --git a/cjl b/cjl
--- a/cjl
+++ b/cjl
@@ -23,18 +23,19 @@ fi
 
 # Tries to fix all Javascript and Python linting errors for you
 if [ "$1" == "lint-fix" ]; then
-  if ! [ -x "$(command -v yapf)" ]; then
-    echo "You must install yapf to auto-fix Python linting errors. python3 -m pip install yapf."
+  if ! [ -x "$(command -v autopep8)" ]; then
+    echo "You must install autopep8 to auto-fix Python linting errors. python3 -m pip install autopep8."
   fi
   if ! [ -x "$(command -v npm)" ]; then
     echo "You must install node & npm to install front-end dependencies and auto-fix Javascript linting errors."
   fi
 
   echo " >> Automatically fixing linting errors <<" && echo ""
-  cd ./src/web_client && npm install && npm run lintfix && cd ../.. && yapf -ir . && \
+  cd ./src/web_client && npm install && npm run lintfix && cd ../.. && autopep8 -ir . && \
   echo "Done!"
   exit
 fi
+
 
 
 
